services:
  traefik:
    image: traefik:v3.6
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./traefik/certs/fullchain.pem:/cert.pem    # only for .local development use
      - ./traefik/certs/privkey.pem:/key.pem       # only for .local development use
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.role == manager"
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE="Host(`\{\{ trimPrefix `/` .Name \}\}.${domain}`)"
    # - CF_DNS_API_TOKEN=$WT_CLOUDFLARE_TOKEN      # only for real domain use

  mongo:
    image: mongo:4.4
    networks:
      - mongo
    volumes:
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  local_worker:
    image: xarthisius/girder_wholetale:latest
    networks:
      - celery
      - mongo
    depends_on:
      - mongo
      - redis
      - girder
    volumes:
      - ./volumes:/srv/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
    extra_hosts:
      - "girder.${WT_DOMAIN}:host-gateway"
    environment:
      - DOMAIN=$WT_DOMAIN
      - DASHBOARD_URL=https://dashboard.${WT_DOMAIN}
      - GIRDER_HOST=0.0.0.0
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_WORKER_BACKEND=redis://redis/
      - GIRDER_WORKER_BROKER=redis://redis/
      - GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379/
      - GOSU_USER=${girder_uid}:${girder_gid}:${docker_group}
      - HOSTDIR=/
    entrypoint: ["/usr/bin/tini", "--", "/docker-entrypoint-worker.sh"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  girder:
    image: xarthisius/girder_wholetale:latest
    networks:
      - traefik-net
      - celery
      - mongo
    depends_on:
      - mongo
      - redis
      - traefik
    volumes:
      - ./volumes:/srv/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - DOMAIN=$WT_DOMAIN
      - DASHBOARD_URL=https://dashboard.${WT_DOMAIN}
      - GIRDER_HOST=0.0.0.0
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_WORKER_BACKEND=redis://redis/
      - GIRDER_WORKER_BROKER=redis://redis/
      - GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379/
      - GOSU_USER=${girder_uid}:${girder_gid}:${docker_group}
      - HOSTDIR=/
    entrypoint: ["/usr/bin/tini", "--", "/docker-entrypoint.sh"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.girder.rule=Host(`girder.${WT_DOMAIN}`)"
        - "traefik.http.routers.girder.entrypoints=websecure"
        - "traefik.http.routers.girder.tls=true"
        - "traefik.http.routers.girder.tls.certresolver=default"
        - "traefik.http.routers.girder.tls.domains[0].main=${WT_DOMAIN}"
        - "traefik.http.routers.girder.tls.domains[0].sans=*.${WT_DOMAIN}"
        - "traefik.http.services.girder.loadbalancer.server.port=8080"
        - "traefik.http.services.girder.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.http.middlewares.girder.forwardauth.address=http://girder:8080/api/v1/user/authorize/"
        - "traefik.http.middlewares.girder.forwardauth.trustforwardheader=true"

  logger:
    image: wholetale/instance_logger:latest
    networks:
      - celery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  redis:
    image: redis:7-bullseye
    networks:
      - celery
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  dashboard:
    image: wholetale/ngx-dashboard:latest
    networks:
      - traefik-net
    depends_on:
      - girder
      - traefik
    extra_hosts:
      - "girder.${WT_DOMAIN}:host-gateway"
    environment:
      - GIRDER_API_URL=https://girder.${WT_DOMAIN}/api/v1
      - AUTH_PROVIDER=Globus
      - DATAONE_URL=https://cn.dataone.org/cn/v2
      - RTD_URL=https://wholetale.readthedocs.io/en/latest
      - DASHBOARD_DEV=true
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.${WT_DOMAIN}`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
  
  instance-errors:
    image: wholetale/custom-errors:latest
    networks:
      - traefik-net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.instance-errors.rule=HostRegexp(`{host:tmp-.*}`)"
        - "traefik.http.routers.instance-errors.entrypoints=websecure"
        - "traefik.http.routers.instance-errors.tls=true"
        - "traefik.http.routers.instance-errors.priority=1"
        - "traefik.http.routers.instance-errors.middlewares=error-pages-middleware"
        - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
        - "traefik.http.middlewares.error-pages-middleware.errors.service=instance-errors"
        - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html"
        - "traefik.http.services.instance-errors.loadbalancer.server.port=80"
        - "traefik.docker.network=wt_traefik-net"

  registry:
    image: registry:2.6
    networks:
      - traefik-net
    volumes:
      - ./volumes/registry:/var/lib/registry
      - ./registry/auth:/auth:ro
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/registry.password
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.${WT_DOMAIN}`)"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.services.registry.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"

  images:
    image: registry:2.6
    networks:
      - traefik-net
    volumes:
      - ./volumes/registry:/var/lib/registry:ro
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.images.rule=Host(`images.${WT_DOMAIN}`)"
        - "traefik.http.routers.images.rule=Method(`GET`)"
        - "traefik.http.routers.images.entrypoints=websecure"
        - "traefik.http.routers.images.tls=true"
        - "traefik.http.services.images.loadbalancer.server.port=5000"
        - "traefik.http.services.images.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"

  celery_worker:
    image: xarthisius/gwvolman:latest
    networks:
      - celery
    user: "1000:999"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/tmp:/tmp
    extra_hosts:
      - "images.${WT_DOMAIN}:host-gateway"
      - "registry.${WT_DOMAIN}:host-gateway"
      - "girder.${WT_DOMAIN}:host-gateway"
    environment:
      - GOSU_USER=${girder_uid}:${girder_gid}:${docker_group}
      - DOMAIN=${WT_DOMAIN}
      - REPO2DOCKER_VERSION=${r2d_version}
      - GIRDERFS_IMAGE=${girderfs_image}
      - TRAEFIK_NETWORK=wt_traefik-net
      - TRAEFIK_ENTRYPOINT=websecure
      - REGISTRY_USER=${registry_user}
      - REGISTRY_URL=https://registry.${WT_DOMAIN}
      - REGISTRY_PASS=${registry_pass}
      - WT_LICENSE_PATH=${PWD}/volumes/licenses
      - WT_VOLUMES_PATH=${PWD}/volumes
      - SWARM_NODE_ID={{.Node.ID}}
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
    command: -c 3

  dagster_web:
    image: xarthisius/dagster:latest
    depends_on:
      - postgresql
    entrypoint: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "workspace.yaml"]
    networks:
      - traefik-net
      - dagster
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dagster.rule=Host(`dagster.${domain}`)"
        - "traefik.http.routers.dagster.entrypoints=websecure"
        - "traefik.http.routers.dagster.tls=true"
        - "traefik.http.services.dagster.loadbalancer.server.port=3000"
        - "traefik.http.services.dagster.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
    environment:
      - DAGSTER_POSTGRES_USER=postgres_user
      - DAGSTER_POSTGRES_PASSWORD=postgres_password
      - DAGSTER_POSTGRES_DB=postgres_db
    extra_hosts:
      - "girder.${domain}:host-gateway"
    volumes:
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/io_manager_storage:/tmp/io_manager_storage

  dagster_daemon:
    image: xarthisius/dagster:latest
    entrypoint: ["dagster-daemon", "run"]
    environment:
      - DAGSTER_POSTGRES_USER=postgres_user
      - DAGSTER_POSTGRES_PASSWORD=postgres_password
      - DAGSTER_POSTGRES_DB=postgres_db
    volumes:
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/io_manager_storage:/tmp/io_manager_storage
    extra_hosts:
      - "girder.${domain}:host-gateway"
    networks:
      - dagster
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  postgresql:
    image: postgres:11
    deploy:
      replicas: 1
    networks:
      - dagster
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db

networks:
  traefik-net:
    driver: overlay
  mongo:
    driver: overlay
    attachable: true
  celery:
    driver: overlay
    attachable: true
  dagster:
    driver: overlay
    attachable: true

volumes:
  mongo-data: {}
  mongo-cfg: {}
